version: '3.9'

services:
  target_1:
    build:
      context: .
      dockerfile: ./target/Dockerfile
    ports:
     - "9997:9997"
    # volumes:  
    #   - ./:/usr/src/app
    # command: bash -c "mv /usr/src/app/events.log /usr/src/app/events1.log"
  target_2:
    build:
      context: .
      dockerfile: ./target/Dockerfile
    ports:
     - "9998:9997"
    # volumes:
    #  - ./:/usr/src/app
    # command: bash -cs "mv /usr/src/app/events.log /usr/src/app/events1.log"
    # depends_on:
    #  - "target_1"
  splitter:
    build:
      context: .
      dockerfile: ./splitter/Dockerfile
    ports:
     - "9996:9997"
    depends_on:
     - "target_1"
     - "target_2"
  agent:
    build:
      context: .
      dockerfile: ./agent/Dockerfile
    ports:
     - "9995:9995"
    depends_on:
     - "splitter"
  

