version: '3.9'

services:
  target_1:
    build:
      context: .
      dockerfile: ./target/Dockerfile
    ports:
     - "9997:9997"
    container_name: 'target_1'

  target_2:
    build:
      context: .
      dockerfile: ./target/Dockerfile
    ports:
     - "9998:9997"
    container_name: 'target_2'

  splitter:
    build:
      context: .
      dockerfile: ./splitter/Dockerfile
    ports:
     - "9996:9997"
    depends_on:
     - "target_1"
     - "target_2"
    container_name: 'splitter'
    
  agent:
    build:
      context: .
      dockerfile: ./agent/Dockerfile
    ports:
     - "9995:9995"
    depends_on:
     - "splitter"
    container_name: 'agent'
  

