
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Project Dependencies
        run: npm install

      - name: Bring up target,splitter, and agent containers
        run: docker-compose up -d

      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Retrieve data from containers
        run: npm run data

      - name: Bring down target, splitter and agent containers
        run: docker-compose down

      - name: Create Artifact of Output Folder
        uses: actions/upload-artifact@master
        with:
          name: project
          path: ./output/
          retention-days: 1
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Project Dependencies
        run: npm install

      - name: Get Output Folder Artifact
        uses: actions/download-artifact@master
        with:
          name: project
          path: ./output/

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Create Artifact of Test Report
        uses: actions/upload-artifact@master
        with:
          name: report
          path: ./mochawesome-report/
          retention-days: 1

  report: 
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v2

      - name: Get Test Report Artifact
        uses: actions/download-artifact@master
        with:
          name: report
          path: ./mochawesome-report/

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
